### ISSUE TITLE
Authentication not found in Apache 2.2.x

### ISSUE THREAD

**Issue by eduardolapa** [viniciussanchez/horse-basic-auth#10]
I wrote the same authentication program in the quickstart example,
when i run as a standalone application works very well, but when i run as a cgi in apache i got the error
"Authentication not found".
I using Lazarus 2.0.12 and FPC 3.2.0

**Comment by kabiri** [comment]
I have same problem
in line 99
change 
`if not LBasicAuthenticationEncode.ToLower.StartsWith(BASIC_AUTH) then`
to
`if not LBasicAuthenticationEncode.ToLower.Trim.StartsWith(BASIC_AUTH) then`
