### ISSUE TITLE
Incluir uma lista de Rotas autorizadas JustRoutes in IHorseBasicAuthenticationConfig

### ISSUE THREAD

**Issue by drsmoreira** [viniciussanchez/horse-basic-auth#14]
Boa tarde!

  Na minha API, eu tinha uma função de autenticar o usuário e senha com Basic Autentication e os demais serviços com o Token que a função de login retornava, com o novo Horse 3.0, eu não consigo mais colocar o basic autentication somente em uma rota como fazia antigamente, por isso, acabei criando uma lista de rotas para que o basic autentication se eu informar rotas especificas, ele só valide as da lista, caso não tenha nenhuma, ele deixe validar todas as rotas, exceto as que estão no skiproute.

[SugestaoInclusaoBasicAutentication.txt](https://github.com/HashLoad/horse-basic-auth/files/8484712/SugestaoInclusaoBasicAutentication.txt)

**Comment by viniciussanchez** [comment]
> "com o novo Horse 3.0, eu não consigo mais colocar o basic autentication somente em uma rota como fazia antigamente"

Consegue sim...

**Comment by viniciussanchez** [comment]
Mas acredito que a ideia seja válida sim. Vou colocar para a próxima versão para análise

**Comment by drsmoreira** [comment]
> > "com o novo Horse 3.0, eu não consigo mais colocar o basic autentication somente em uma rota como fazia antigamente"
> 
> Consegue sim...

E estudando mais a ferramenta, consegui colocando o AddCallBack, funcionou perfeitamente. 
Me desculpa e obrigado pela resposta, parabéns a você e a equipe, ferramenta é fantastica.
