### ISSUE TITLE
SkipRoutes bug path params

### ISSUE THREAD

**Issue by viniciussanchez** [viniciussanchez/horse-basic-auth#15]
Bug with path params in SkipRoutes, example:
```
/users/:id
/products/:id
```

**Comment by drsmoreira** [comment]
Olá

Por enquanto, nos meus projetos, para contornar esse bug, eu fiz a seguinte modificação em anexo, se puder analisar e se estiver conforme o padrão da ferramenta, implementar. 

var
  LRoute : string;
begin
  LPathInfo := AHorseRequest.RawWebRequest.PathInfo;
  if LPathInfo = EmptyStr then
    LPathInfo := '/';
  for LRoute in Config.SkipRoutes do
    begin
      if Pos(LRoute, LPathInfo) > 0 then
        begin
          ANext();
          Exit;
        end;
    end;

**Comment by viniciussanchez** [comment]
Obrigado @drsmoreira vamos analisar

**Comment by andre-djsystem** [comment]
Corrigido no commit https://github.com/HashLoad/horse-basic-auth/commit/84ff17f484adc814212296a2796dfdf484709a11
