### ISSUE TITLE
Não reconhece o header  no CGI gerado pelo lazarus

### ISSUE THREAD

**Issue by mbertolani** [viniciussanchez/horse-basic-auth#16]
mesmo informando o header o CGI retorna "Authorization not found"

**Comment by viniciussanchez** [comment]
Tente seguir esse material...
https://youtu.be/yn4GbOyGAus
Por padrão os Headers no CGI vem bloqueado

**Comment by viniciussanchez** [comment]
@dliocode isso foi resolvido não foi, com a IA que você viu?

**Comment by dliocode** [comment]
@viniciussanchez que eu saiba o Lazarus está funcionando, o problema está na compilação no Delphi, até no final de semana eu vou subir um PR ajustando isso para quem usa o Delphi.

**Comment by viniciussanchez** [comment]
@dliocode deu certo isso?

**Comment by CarlosHe** [comment]
No CGI, o esquema é um pouco diferente quando se trata de header. Os headers são repassados por variáveis de ambiente para a aplicação. Foi realizado uma modificação no Horse recentemente para poder listar os headers da aplicação em CGI. Ainda não foi liberado uma versão definitiva, mas creio eu que logo vai ser anunciado!

Assim que for liberado uma release nova, ainda vai ser preciso fazer uma pequena configuração no seu Apache, para poder receber o header de Authorization (por padrão, não é repassado o header Authorization). Para isso, precisa modificar as configurações do seu Apache para receber.

Basta abrir o arquivo httpd.conf e incluir a linha:

SetEnvIfNoCase Authorization "(.+)" HTTP_AUTHORIZATION=$1
