### ISSUE TITLE
Criar Tag 2.0 para Lazarus.

### ISSUE THREAD

**Issue by chacalfloripa** [viniciussanchez/horse-basic-auth#4]
Olá, estamos usando o Boss para gerenciar as dependências do nosso projeto, mas notamos que o Basic auth ainda não tem uma Tag 2.0 para a compatibilidade com Lazarus.
Se puder criar ajudaria muito.

Abs
Ismael

**Comment by viniciussanchez** [comment]
Olá @chacalfloripa o Boss ainda não é compatível com o Lazarus, por isso não criamos

**Comment by viniciussanchez** [comment]
Liberado a release 1.1.2

**Comment by chacalfloripa** [comment]
@viniciussanchez  estou usando mesmo sem a integração com a IDE, tem me ajudado bastante.
Obrigado.
