### ISSUE TITLE
Basic authentication não compila no lazarus

### ISSUE THREAD

**Issue by mvidalsistemas** [viniciussanchez/horse-basic-auth#6]
THorse.Use(HorseBasicAuthentication(
function(const AUsername, APassword: string): Boolean   
begin
Result := AUsername.Equals('user') and APassword.Equals('password');
end));

Prezados quando tento executar no Lazarus tenho o retorno dos seguintes erros
pedido.lpr(23,1) Error: Illegal expression
pedido.lpr(23,9) Fatal: Syntax error, ")" expected but "(" found

Tem alguma configuração extra para fazer no lazarus
**A linha 23 é a linha function(const ...**

obrigado

**Comment by viniciussanchez** [comment]
Oi, no Lazarus não tem como passar o callback de validação assim como é feito no Delphi por limitações da própria IDE / Linguagem. Então aconselho você a seguir o exemplo adicionado em https://github.com/HashLoad/horse-basic-auth/tree/master/samples/lazarus que vai funcionar.
