### ISSUE TITLE
HorseBasic Authentication Error

### ISSUE THREAD

**Issue by kabiri** [viniciussanchez/horse-basic-auth#9]
when i add this line to my project and open Chrome delphi show error : Project Server_Test.exe raised exception class EListError with message 'Item not found'.

 THorse.Use(HorseBasicAuthentication(
  function(const AUsername, APassword: string): Boolean
  begin
    Result := AUsername.Equals('user') and APassword.Equals('pass');
  end));

**Comment by viniciussanchez** [comment]
There's something wrong, I just tested it and it works fine.

**Comment by viniciussanchez** [comment]
Try to run the project from the "Samples" folder

**Comment by kabiri** [comment]
@viniciussanchez 
i open sample and have same problem 
Project Samples.exe raised exception class EHorseCallbackInterrupted with message ''.
delphi 2 time show this error and Chrome show Unauthorized

delphi 
![error](https://user-images.githubusercontent.com/8082245/141001300-fa292b04-38ef-4af5-b9b9-46bfaf119165.png)
1

**Comment by viniciussanchez** [comment]
When you use the basic authentication middleware, and do not inform the Header Authorization in the request, containing a valid username and password, this exception will pop up.

That's if you're in debug mode. If you click on continue, it will give the message of unauthorized, because the valid username and password were not informed in the Authorization header.

If you enter the data correctly in the request, it will not give the message. That's how it works

**Comment by kabiri** [comment]
Chrome does not open a login page for me and I do not enter a username and password, it only displays the Unauthorized message.
That's right with postman, but I'm building a website
Also how to set up logout, maybe Chrome already has data stored for this port
Do you need me to film the process?

**Comment by viniciussanchez** [comment]
Yes, your browser must have cache.
No need to film.
If you make a request in the browser it would have to appear a small screen asking for the credentials.
If that's not showing up, it's not Horse's or middleware's problem. It's your browser's problem.
Just yesterday I needed to do a test, and the screen appeared for me.

**Comment by kabiri** [comment]
Okay, I'll clear the browser cache and test it
But how do I make a log out?

**Comment by viniciussanchez** [comment]
Logout would be a rule of your frontend application. You need to set this... basically it would remove the site cache containing the username and password that it would no longer request

**Comment by kabiri** [comment]
Is no session recorded?

**Comment by viniciussanchez** [comment]
on the horse no

**Comment by kabiri** [comment]
OK thanks
